stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/mod_qsar_fish_toxicity.csv
    outs:
    - data/raw/mq_fish_toxicity.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/mq_fish_toxicity.csv
    outs:
    - data/processed/train_mq_fish_toxicity.csv
    - data/processed/test_mq_fish_toxicity.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_mq_fish_toxicity.csv
    - data/processed/test_mq_fish_toxicity.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.GradientBoostingRegressor.params.learning_rate
    - estimators.GradientBoostingRegressor.params.max_depth
    - estimators.GradientBoostingRegressor.params.n_estimators
    - estimators.GradientBoostingRegressor.params.subsample
    #metrics:
    #- report/scores.json:
    #    cache: false
    #- report/params.json:
    #    cache: false
    #outs:
    #- saved_models/model.joblib 

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py