base:
  project: fish toxicity prediction project
  random_state: 44
  target_col: responseLC50

data_source:
  s3_source: data_given/mod_qsar_fish_toxicity.csv

load_data:
  raw_dataset_csv: data/raw/mq_fish_toxicity.csv

split_data:
  train_path: data/processed/train_mq_fish_toxicity.csv
  test_path: data/processed/test_mq_fish_toxicity.csv
  test_size: 0.2

estimators:
  GradientBoostingRegressor:
    params:
      learning_rate: 0.04 #0.06 #0.01
      max_depth: 20 #15 #10
      n_estimators: 600 #250 #500
      subsample: 0.55 #0.6 #0.5

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: FishToxicityPred Regression
  run_name: mlops
  registered_model_name: GBRFishToxicModel
  remote_server_uri: http://127.0.0.1:8001